name: heron
description: A static site generator.
version: 0.1.1
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/heron

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  markdown: ^0.11.2
  mustache: ^0.2.5
  resource: ^2.1.0
  yaml: ^2.1.12
  stack_trace: ^1.7.0

dev_dependencies:
  test: ^0.12.18
  scheduled_test: ^0.12.9
